-- Core A1 transaction state machine: INITIATED -> VALIDATED -> PROCESSED | REJECTED.
--
-- NAMING: account identifiers are called ACCOUNT, not IBAN. Uzbekistan is not in the IBAN
-- registry; domestic accounts are 20-digit numbers. The column is sized VARCHAR2(34) so that
-- a genuine IBAN also fits, which is what a cross-border ISO 20022 leg would carry.
-- Identical in every observability mode, so that the business workload under test is
-- byte-for-byte the same and only the instrumentation differs (internal validity).

CREATE TABLE TXN_A1 (
  TXN_ID       NUMBER(19)   GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TXN_REF      VARCHAR2(64) NOT NULL,
  DEBIT_ACCOUNT   VARCHAR2(34) NOT NULL,
  CREDIT_ACCOUNT  VARCHAR2(34) NOT NULL,
  AMOUNT       NUMBER(19,4) NOT NULL,
  CURRENCY     VARCHAR2(3)  DEFAULT 'UZS' NOT NULL,
  STATUS       VARCHAR2(16) NOT NULL,
  CHANNEL      VARCHAR2(24),
  REJECT_CODE  VARCHAR2(16),
  CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  VERSION      NUMBER(10)   DEFAULT 0 NOT NULL,
  CONSTRAINT UQ_TXN_A1_REF   UNIQUE (TXN_REF),
  CONSTRAINT CK_TXN_A1_STATE CHECK (STATUS IN ('INITIATED','VALIDATED','PROCESSED','REJECTED'))
);

CREATE INDEX IX_TXN_A1_STATUS ON TXN_A1 (STATUS, UPDATED_AT);

CREATE TABLE LEDGER_ENTRY (
  ENTRY_ID   NUMBER(19)   GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TXN_ID     NUMBER(19)   NOT NULL,
  ACCOUNT_NO VARCHAR2(34) NOT NULL,
  DIRECTION  VARCHAR2(1)      NOT NULL,
  AMOUNT     NUMBER(19,4) NOT NULL,
  POSTED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_LEDGER_TXN  FOREIGN KEY (TXN_ID) REFERENCES TXN_A1 (TXN_ID),
  CONSTRAINT CK_LEDGER_DIR  CHECK (DIRECTION IN ('D','C'))
);

CREATE INDEX IX_LEDGER_TXN ON LEDGER_ENTRY (TXN_ID);

-- NOORDER avoids the global RAC sequence-ordering latch; ordering is carried by
-- EVENT_SEQ semantics, not by sequence monotonicity across instances.
CREATE SEQUENCE SEQ_A1_EVENT START WITH 1 INCREMENT BY 1 CACHE 1000 NOORDER;
